### ISSUE TITLE
built electron app does not work: Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Fr4nd4lf** [ThisNameNotUsed/cesium-electron-webpack#1]
Hi I am very thankful for your code. I am also trying to build a desktop app with cesium and this saved me a lot of time.

But when I am building the electron application with `yarn dist`  and then try to run it the globe does not appear and I get a lot of error notifications:
`index.html/Assets/ap…rrainHeights.json:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`
`index.html/Widgets/InfoBox/InfoBoxDescription.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND `
...
`index.html/Workers/transferTypedArrayTest.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`

Did you experience similar problems? And how did you solve them?

**Comment by ThisNameNotUsed** [comment]
Did you read the README to this project? I still have to comment out some of the resources used in one of the .css files to get the project to build. It's an open issue I intend to get to when I can. As you can probably tell from this late response I haven't had a lot of time to update this project.

**Comment by Fr4nd4lf** [comment]
Yes I have read the README and I used your workaround for the missing resources. When I run the project with yarn dev everything works fine. 
But when I use yarn dist to build the application I get the above mentioned error.

I decided to continue my project without using webpack. So I dont need a fast solution for this issue.

**Comment by ThisNameNotUsed** [comment]
I finally came back to this and figured it out. Yarn's .yarnclean file is like a git .ignore file for your package manager. I had to remove 'images' from it so that yarn would correctly download Cesium's image folders. The image is no longer missing and everything builds correctly after yarn install and upgrade commands.
